name: gs-view
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - cudatoolkit=11.8
  - pytorch-cuda=11.8
  - tqdm
  - click
  - pillow
  - imageio
  - requests
  - opencv
  - scipy
  - pandas
  - plyfile
  - pip:
    - imgui==2.0.0
    - imgui_bundle
    - glfw
    - pyopengl
    - imageio-ffmpeg
    - gaussian-splatting/submodules/diff-gaussian-rasterization
    - gaussian-splatting/submodules/simple-knn
    - numpy==1.23.1
    - imagecodecs[all]