active_sh_degree: 0
attributes:
- contract: false
  method: exr
  name: _xyz
  normalize: false
  params:
    compression: zip
  quantize: 13
- method: jpeg-xl
  name: _features_dc
  normalize: true
  params:
    level: 90
- contract: false
  method: exr
  name: _scaling
  normalize: false
  params:
    compression: none
  quantize: 6
- method: exr
  name: _rotation
  normalize: false
  params:
    compression: zip
  quantize: 6
- contract: false
  method: exr
  name: _opacity
  normalize: true
  params:
    compression: none
  quantize: 5
max_sh_degree: 0
name: exr_jxl_quant
